### ISSUE TITLE
Access to low level (cairo) context

### ISSUE THREAD

**Issue by drug007** [BlackEdder/ggplotd#1]
to have opportunity of adding custom information. For example I have several sets of points and I need to draw an error ellipse for every point set. I guess it would be simpler to do using a cairo context.

**Comment by BlackEdder** [comment]
Any geom\* Function has direct access to the cairo context. Have a look at geomPoint and geomLine.

**Comment by drug007** [comment]
Ah, yes, didn't look.

P.S. I have another small question but don't know where to ask it - here in issues or in DlangScience. For example I need to have uniform scale on all axes.

**Comment by BlackEdder** [comment]
Setting axis is being worked on. I wanted to add support for logarithmic axis at the same time. Problem is to do that we can't rely on cairo.Context anymore, so it will be a bit of a bigger job.

**Comment by BlackEdder** [comment]
The latest release added better control of axes. Closing this for now.

Did you manage to get a geomEclipse working? Feel free to re open if you need help for that :)
