### ISSUE TITLE
Is there any support for plotting an AA?

### ISSUE THREAD

**Issue by grogancolin** [BlackEdder/ggplotd#2]
So I could just give the Aes struct an AA and it will use the keys as it's "x" and the values as it's "y" axes.

if not, I _think_ should be easy add, as a simple helper function

```
auto data = ["a" : 1.0, "b" : 2.0, "c" : 3.0];
auto aes = hashAes(data);

auto hashAes(T)(T data){
   // ... some code check if T is indeed an AA
   auto xVals = data.keys;  
   auto yVals = data.values;   // not sure if these will be in the same order (i.e. xVals[0] is the X for yVals[0]. If not, simple enough solution to loop over xVals appending to an array

   return Aes!(typeof(xVals), "x", typeof(yVals), "y")(xVals, yVals);
}
```

**Comment by BlackEdder** [comment]
This would be good to have. Might be worth to add a custom constructor. In essence Aes is a named tuple, so if you can convert to named tuple you can convert to Aes. I'm on holiday at the moment, so might take some time. Of course pull request is always welcome.

**Comment by BlackEdder** [comment]
Thinking some more about this, one would need to access the keys of the associative array at compile time. Don't think that is possible?

Will have to think more about this.

**Comment by BlackEdder** [comment]
Closing this. 

Having considered it I think it is outside the scope of ggplotd for now to try to handle all types of data layout (some of which are bound to be contra dictionary). 

Note that one is not required to use the `Aes` type. Any type with the correct fields can be used (see README for a quick example).
