### ISSUE TITLE
API without typeof

### ISSUE THREAD

**Issue by wilzbach** [BlackEdder/ggplotd#25]
D has static types so instead of 

``` d
gg.put( geomPoint( Aes!(typeof(xs), "x", typeof(ys2noise), "y", string[],
        "colour" )( xs, ys2noise, ("b").repeat(xs.length).array) ));
```

it should be possible to do

``` d
gg.put( geomPoint( "x", "y", "colour" )( xs, ys2noise, ("b").repeat(xs.length).array) ));
```

which would be a lot nicer.
Btw ideally as an API user I would like to use something similar to:

``` d
geomPoint(xs, ys).put(gg);
```

And if there are more configs

``` d
Config config = {color: "red"}; 
geomPoint(xs, ys, config).put(gg);
```

Btw there is a [DIP in work](https://github.com/dlang/DIPs/pull/22) that could allow the following:

```
geomPoint(xs, ys, {color: "red"}).put(gg);
```

**Comment by BlackEdder** [comment]
> D has static types so instead of
> 
> gg.put( geomPoint( Aes!(typeof(xs), "x", typeof(ys2noise), "y", string[],
>         "colour" )( xs, ys2noise, ("b").repeat(xs.length).array) ));
> it should be possible to do
> 
> gg.put( geomPoint( "x", "y", "colour" )( xs, ys2noise, ("b").repeat(xs.length).array) ));
> which would be a lot nicer.

The library is really meant to make it easier to plot your own data, where the data can have many dimensions and you want to plot the first value as x, second y and third to be the colour. Think of a data table where you have many columns (dimensions).( Also see the using your own data section). In that case it is more annoying to have to pull your data apart than just to plot them. I do agree that something like `aes("x", "y")(xs, ys)` would be nice and I will try to add such a wrapper. I'll also reorganise the readme to make this usage a bit more clear. 

> Btw ideally as an API user I would like to use something similar to:
> 
> geomPoint(xs, ys).put(gg);

It should be easy enough to add a free standing put function that takes an inputrange with elemtype Geom and a GGPlotD struct. I'll add that (PR's also very welcome of course).

> And if there are more configs
> 
> Config config = {color: "red"}; 
> geomPoint(xs, ys, config).put(gg);

Like explained above in general the colour is meant to represent a third dimension of your data. In that case you want all the points have a different colour, not all be red. Of course currently you can do what you propose using mergeRange (see the data section).

**Comment by BlackEdder** [comment]
> I do agree that something like aes("x", "y")(x, y) would be nice and I will try to add such a wrapper.

I suddenly remember that I didn't add this, because I was never able to get it to work. Any ideas on how to let it infer the types. Currently I am doing this:

``` D
template aes(Specs...)
{
    // Collect field names. Static map it with the rest to make a new tuple
   alias Specs[Specs.length/2 .. $] FieldTypes;

    template tupleType(Specs...)
    {
        static if (Specs.length == 0) {
            alias TypeTuple!() tupleType;
        } else {
            alias TypeTuple!(Specs[Specs.length/2], Specs[0],
                    tupleType!(Specs[1..Specs.length/2], 
                    Specs[(Specs.length/2+1)..$]))
                tupleType;
        }
    }

    pragma(msg, tupleType!Specs); // tuple((int), "y", (int), "x")

    alias TupleTypes = tupleType!Specs;

    auto aes(FieldTypes args)
    {
        import std.typecons : Tuple;
        return Tuple!(TupleTypes)(args);
    }
}

///
unittest
{
    // This works
    auto a = aes!("y", "x", int, int)(1, 2);
    assertEqual( a.y, 1 );
    assertEqual( a.x, 2 );

    // This does not, because it doesn't know to infer int, int
    auto a1 = aes!("y", "x")(1, 2);
    assertEqual( a1.y, 1 );
    assertEqual( a1.x, 2 );
}
```

So the first test works, second fails. The pragma(msg, tupleType!Specs) returns `tuple("x", "y")` and I get the following compile error.

```
source/ggplotd/aes.d(68,10): Error: tuple Specs is used as a type
source/ggplotd/aes.d(82,15): Error: template instance ggplotd.aes.aes!("y", "x") error instantiating
```

**Comment by BlackEdder** [comment]
Never mind! Got it to work :)

**Comment by BlackEdder** [comment]
Working on this in PR #26
