### ISSUE TITLE
Axes at the center

### ISSUE THREAD

**Issue by ghost** [BlackEdder/ggplotd#3]
Can I put both axes at the center of the plot?

**Comment by BlackEdder** [comment]
Not at the moment. It won't be to hard to implement it though. So might be able to add it within next couple of days.

**Comment by BlackEdder** [comment]
Associated trello card (with checklist containing needed steps) 
https://trello.com/c/o26BRYUs/46-axes-offset

**Comment by BlackEdder** [comment]
Added in 3080f5d396e402c5a3b52a84df06ebc26f4cc025 with xaxisOffset yaxisOffset: (see the axes example in README)

**Comment by ghost** [comment]
Thank you.
