### ISSUE TITLE
OSX: Library load failed: libatk-1.0.dylib

### ISSUE THREAD

**Issue by timotheecour** [BlackEdder/ggplotd#32]
object.Exception@../../../../.dub/packages/gtk-d-3.3.1/gtk-d/src/gtkc/Loader.d(123): Library load failed: libatk-1.0.dylib

README.md only shows `sudo apt-get install libcairo2-dev` as a dependency; what about osx? i did do brew install cairo FWIW but should i also have `brew install atk` ?

EDIT: after that i still get:
```
$binary
object.Exception@../../../../.dub/packages/gtk-d-3.3.1/gtk-d/src/gtkc/Loader.d(123): Library load failed: libatk-1.0.dylib
```

Also tried:
```
DYLD_LIBRARY_PATH=$HOME/homebrew/lib $binary

dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/timothee/homebrew//lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

```

**Comment by BlackEdder** [comment]
Are you trying to install it with gtk support?

On travis it needs the following libraries to build/install:

```
brew install libjpeg cairo gtk+3
```

**Comment by timotheecour** [comment]
will try your suggestion.

Regardless, see also relevant discussion in http://forum.dlang.org/thread/mailman.519.1480285208.9448.digitalmars-d-learn@puremagic.com
how to debug exceptions/asserts thrown in module constructors?

**Comment by timotheecour** [comment]
> On travis it needs the following libraries to build/install:

This didn't help:
still getting object.Exception@../../../../../../.dub/packages/gtk-d-3.3.1/gtk-d/src/gtkc/Loader.d(123): Library load failed: libatk-1.0.dylib

to reproduce: (pasting from a part of http://forum.dlang.org/thread/mailman.519.1480285208.9448.digitalmars-d-learn@puremagic.com)

main.d:
import ggplotd.gtk;
void main(){
}


dub.json:
{
 "targetType": "executable",
 "sourcePaths":["."],

 "dependencies": {
 "ggplotd": ">=1.1.0",
 },

 "subConfigurations": {
  "ggplotd": "ggplotd-gtk",
 },
 "buildRequirements": ["allowWarnings"],
}

**Comment by timotheecour** [comment]
NOTE: i do have /Users/timothee/homebrew//lib/libatk-1.0.dylib but dlopen isn't able to find it based on just libatk-1.0.dylib alone and, as explained above, setting DYLD_LIBRARY_PATH causes other issues. 

The following worked in my case:
edit /Users/timothee/.dub/packages//gtk-d-3.3.1/gtk-d/src/gtkc/Loader.d :
edit
private void* pLoadLibrary(string libraryName, RTLD flag = RTLD.NOW):

```
auto libraryName2=`/Users/timothee/homebrew/lib/`~libraryName;
void* handle = dlopen(cast(char*)toStringz(libraryName2), flag);
if(!handle){
  import std.string;
  string temp=dlerror().fromStringz.idup;
  assert(0, temp);
}
```

the code should be improved to autodetect the path to that library, or at least provide an environment variable for that (but not DYLD_LIBRARY_PATH)

**Comment by timotheecour** [comment]
Also note: if `brew install libjpeg cairo gtk+3` is required on OSX it should be clear in README.md

**Comment by BlackEdder** [comment]
> Also note: if brew install libjpeg cairo gtk+3 is required on OSX it should be clear in README.md

I don't have a mac so not really sure if it is required. That's just how I got it to work. I hesitate to add things to the readme that I can't fully test myself. If you can confirm that all three are needed for the gtk build then I can add a section (PR is always welcome as well :) )

**Comment by BlackEdder** [comment]
By the way if you don't need gtk support it will work fine without it.

**Comment by MikeWey** [comment]
As for GtkD would there be anyway to detect the homebrew path?

* Does homebrew provide environment variables?
* Is the library path always in the same place relative to the brew exactable?
* Are there a few default install paths to check? (~/homebrew, /usr/local, /opt)

I don't have any experience with OSX and homebrew, but it would be great to get this working.

**Comment by BlackEdder** [comment]
> Does homebrew provide environment variables?

There seems to be a $HOMEBREW_ROOT variable.

**Comment by timotheecour** [comment]
IIRC $HOMEBREW_ROOT is not exported by installing homebrew; note, a user
can have multiple homebrew roots; the simplest solution is to either
require a user to set an environment variable specifying the root location
(of his choice), or, assume he put homebrew/bin in his PATH and just call
`brew config|grep HOMEBREW_PREFIX`

On Tue, Nov 29, 2016 at 1:59 PM, Edwin van Leeuwen <notifications@github.com

**Comment by timotheecour** [comment]
also, `brew --prefix` is simpler than `brew config|grep HOMEBREW_PREFIX`

**Comment by BlackEdder** [comment]
@MikeWey would you be ok with calling brew --prefix for gtkd? Or maybe accept a custom environmental variable and update the gtkd readme?

**Comment by MikeWey** [comment]
We could do both `brew --prefix` and the environment variable. Although i'm not that keen on calling an other executable on startup.

For the environment variable, we could use the `GTK_BASEPATH` that we used to use on windows, or `HOMEBREW_ROOT`.

**Comment by timotheecour** [comment]
closed since https://github.com/gtkd-developers/GtkD/issues/164 is closed now
