### ISSUE TITLE
bash autotest.sh: inotify-hookable: command not found

### ISSUE THREAD

**Issue by timotheecour** [BlackEdder/ggplotd#33]
OSX:
```
bash autotest.sh
Linking...
Running ./__test__default__
Random seed: 2067000344
Random seed MCMC: 1226040721
All unit tests have been run successfully.
autotest.sh: line 7: inotify-hookable: command not found
```

**Comment by BlackEdder** [comment]
Any reason you are trying to run autotest.sh? It is only used during development. If you want to use it you need to install inotify-hookable [1]. 

[1] http://search.cpan.org/~avar/App-Inotify-Hookable-0.07/lib/App/Inotify/Hookable.pm
