### ISSUE TITLE
Wrong Tick labels

### ISSUE THREAD

**Issue by Droggelbecher** [BlackEdder/ggplotd#54]
Observed with ggplotd-1.1.6 (via dub).
Code to reproduce some examples:
```
	auto gg = [[18.0, 0.0], [18.1, 1.0], [18.2, 2.0]] // test1.png
	//auto gg = [[18.0, 0.0], [18.5, 1.0], [19.0, 2.0], [19.5, 3.0], [20.0, 4.0]] // test2.png
        //auto gg = [[18.0, 0.0], [19.0, 1.0], [20.0, 2.0], [21.0, 3.0]] // test3.png

		.map!((a) =>
			aes!("x", "y", "colour")(a[0], a[1], "red")
		)
		.geomPoint
		.putIn(GGPlotD());
	gg = gg + scale();
	gg.save("test1.png");
```
test1.png:
X-Axis should be .. 18.**0**8 .. 18.12 .. -> String formatting issue?
![test1](https://user-images.githubusercontent.com/118525/50573289-8576eb80-0dd1-11e9-9ea6-91d253558667.png)

test2.png:
No idea whats going on here, the first 19.2 should be a value < 19.0 (My guess would be 18.8)
![test2](https://user-images.githubusercontent.com/118525/50573293-8a3b9f80-0dd1-11e9-9b6c-88207fa46d78.png)

test3.png:
Last x-axis value should be < 21,
alsy y-axis values are messed up completely.
![test3](https://user-images.githubusercontent.com/118525/50573345-76dd0400-0dd2-11e9-8320-caab92f5530a.png)

**Comment by BlackEdder** [comment]
This is fixed in version 1.1.7
