### ISSUE TITLE
Rotating Axes Labels

### ISSUE THREAD

**Issue by burner** [BlackEdder/ggplotd#60]
I have this plot, and I would like to rotate the dates on the x axis.
I couldn't find an option for it.
Is there any way? Or is this a missing feature?

![lines](https://user-images.githubusercontent.com/13327/64336924-08da8380-cfd6-11e9-9155-f16109648ea4.png)

**Comment by BlackEdder** [comment]
I am afraid this is currently a missing feature. 

The ideal solution would be to add it to the theme (similar to how it works in [ggplot2](https://www.datanovia.com/en/blog/ggplot-axis-ticks-set-and-rotate-text-labels/)), but the theme part of ggplotd is pretty sparse and would need a significant amount of work.

**Comment by BlackEdder** [comment]
Merge request #60 introduced some bugs that have now been fixed (and axisLabelAngle has been renamed to axisTextAngle for consistency).
